# Generated by Django 2.0.8 on 2018-09-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='complete',
        ),
    ]
